import type { Metadata } from 'next'
import { Work_Sans } from 'next/font/google'
import './globals.css'
/* import { Providers } from './providers' */
import { Header } from '@/components/header/Index'
import { Footer } from '@/components/footer/Index'

const inter = Work_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pasión por las Finanzas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        {/* <Providers> */}
          <Header />
          {children}
          <Footer />
        {/* </Providers> */}
      </body>
    </html>
  )
}
